# grafana/provisioning/datasources/datasources.yaml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 # Connects to the Prometheus service
    isDefault: true
    access: proxy
    editable: true

  - name: Airflow_PostgreSQL
    type: postgres
    url: postgres:5432 # Connects directly to the postgres service
    database: airflow
    user: airflow # Airflow's PostgreSQL user
    password: airflow # Airflow's PostgreSQL password
    sslmode: disable # For development. For production, consider 'require' or 'verify-full' with proper certs.
    jsonData:
      timescaledb: false
      maxOpenConns: 0
      maxIdleConns: 0
      connMaxLifetime: 14400
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false
    editable: true