# prometheus/prometheus.yml
global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes itself

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187'] # Scrape the postgres exporter service

  # Optional: Scrape Airflow scheduler metrics (if exposed via Prometheus-compatible endpoint)
  # Airflow has a basic health check endpoint, but full metrics often need a StatsD exporter or similar.
  # - job_name: 'airflow_scheduler_health'
  #   static_configs:
  #     - targets: ['airflow-scheduler:8974'] # Health check port